---
abstract: 'GoogleMap plugin'
author:
  - 'Alex Vandiver <alexmv@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.11
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Jifty-Plugin-GoogleMap
no_index:
  directory:
    - share
    - share
    - inc
    - t
requires:
  Jifty: 0
resources:
  license: http://dev.perl.org/licenses/
version: 1.00
